/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/sydmontague/imagemaps")
        credentials {
            username = project.findProperty("gh_user") as String?
            password = project.findProperty("gh_token") as String?
        }
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations)
    api(libs.org.reflections.reflections)
    api(libs.org.javassist.javassist)
    api(libs.net.craftcitizen.imagemaps)
    api(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.org.spigotmc.spigot)
}

group = "com.articreep.pocketknife"
version = "1.7"
description = "Pocketknife"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
