/*
 * This file was generated by the Gradle 'init' task.
 */

paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION

plugins {
    `java-library`
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    id("com.gradleup.shadow") version "8.3.5"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/sydmontague/imagemaps")
        credentials {
            username = project.findProperty("gh_user") as String?
            password = project.findProperty("gh_token") as String?
        }
    }

    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }
}

dependencies {
    api(libs.org.jetbrains.annotations)
    api(libs.org.reflections.reflections)
    api(libs.org.javassist.javassist)
    api(libs.net.craftcitizen.imagemaps) {
        exclude(group = "org.spigotmc", module = "spigot-api")
    }
    compileOnly(libs.com.sk89q.worldedit.worldedit.bukkit)
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")

    paperweight.paperDevBundle("26.2.build.+")
}

group = "com.articreep.pocketknife"
version = "1.8"
description = "Pocketknife"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

paperweight {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// Always build the shadow jar
tasks.build {
    dependsOn(tasks.shadowJar)
}

// Disable default jar
tasks.jar {
    enabled = false
}

tasks.shadowJar {
    archiveFileName.set("Pocketknife-$version.jar")
}
