name: Pocketknife
main: com.articreep.pocketknife.Pocketknife
version: 1.2
author: Arti_Creep
api-version: 1.19
commands:
  funnypickaxe:
    description: Gives the funny pickaxe
    usage: /funnypickaxe
  genesisexplode:
    description: Explode the Pit of Genesis.
    usage: /genesisexplode
  spawnpigsondeath:
    description: Information for the SpawnPigsOnDeath plugin.
    usage: /spawnpigsondeath
