name: Pocketknife
main: com.articreep.pocketknife.Pocketknife
version: 1.2
author: Arti_Creep
api-version: 1.19
commands:
  pocketknife:
    description: Used to access various experiments from Pocketknife.
    usage: /pocketknife <feature> <args>
